### ISSUE TITLE
Index out of bound.

### ISSUE THREAD

**Issue by manojmaity** [T1T4N/NVNC#14]
While running the project in debug mode, getting index out of bound in PixelGrabber.CopyPixels method.

Stack Trace :
   at NVNC.Utils.PixelGrabber.CopyPixels(Int32[] pixels, Int32 scanline, Int32 x, Int32 y, Int32 w, Int32 h) in C:\Users\Maity\Downloads\VNC\NVNC\NVNC-master\NVNC\Utils\PixelGrabber.cs:line 406
   at NVNC.Utils.ScreenTree.QuadNode.GenerateChildren() in C:\Users\Maity\Downloads\VNC\NVNC\NVNC-master\NVNC\Utils\ScreenTree\QuadNode.cs:line 240
   at NVNC.Utils.ScreenTree.QuadNode..ctor(Rectangle2 bounds, Int32[] data) in C:\Users\Maity\Downloads\VNC\NVNC\NVNC-master\NVNC\Utils\ScreenTree\QuadNode.cs:line 35
   at NVNC.Utils.ScreenTree.QuadTree.BFSLowest() in C:\Users\Maity\Downloads\VNC\NVNC\NVNC-master\NVNC\Utils\ScreenTree\QuadTree.cs:line 121
   at NVNC.Utils.ScreenTree.QuadTree..ctor(Rectangle2 screenSize, Int32[] pixels, Int32 minTileHeight, Int32 minTileWidth) in C:\Users\Maity\Downloads\VNC\NVNC\NVNC-master\NVNC\Utils\ScreenTree\QuadTree.cs:line 32
   at NVNC.Utils.ScreenHandler..ctor(Rectangle screen, Boolean hashOnlyCompare) in C:\Users\Maity\Downloads\VNC\NVNC\NVNC-master\NVNC\Utils\ScreenHandler.cs:line 40
   at NVNC.VncServer.Start() in C:\Users\Maity\Downloads\VNC\NVNC\NVNC-master\NVNC\VncServer.cs:line 81
   at VNCTest.Program.Main(String[] args) in C:\Users\Maity\Downloads\VNC\NVNC\NVNC-master\NVNC Example\Program.cs:line 15

**Comment by mattiaorsi** [comment]
same problem here... 
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in NVNC.dll
in PixelGrabber.cs line 422 (index is out of range)

**Comment by voicub** [comment]
Does anybody solved the error?

**Comment by XOTTABY4** [comment]
i'm have same problem, some body solved the error???

**Comment by voicub** [comment]
Check this https://github.com/T1T4N/NVNC/issues/1. It helped me

**Comment by XOTTABY4** [comment]
Thanks, it start but im see only first screen and its all? maybe you now how fix it??????

**Comment by voicub** [comment]
Hi after following this link https://github.com/T1T4N/NVNC/issues/6 the server starting to work but have a terrible lag. The screen update is not in real time and is displaying a lot of graphical glitches. As a client I was used VncSharp nuget package.

**Comment by DiegoDionisio** [comment]
Same problem here, terrible lag.

**Comment by ali-hm** [comment]
any solution?

**Comment by T1T4N** [comment]
Fixed in latest commit.
